name: Build & Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get previous image version
      id: get-previous-version
      run: |
        # Get the latest version from the Docker Hub repository
        PREVIOUS_VERSION=$(docker pull -q ${{ secrets.DOCKERHUB_USERNAME }}/weatherapi:latest | sed -n 's/Digest: sha256:\(.*\)/\1/p')
        echo "::set-output name=previous_version::$PREVIOUS_VERSION"

    - name: Login to Docker Hub
      id: login-docker-hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build, tag, and push the image to Docker Hub
      id: build-image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_REPOSITORY: weatherapi
        IMAGE_TAG: ${{ steps.get-previous-version.outputs.previous_version + 1 }}
      run: |
        # Build a docker container and push it to Docker Hub
        docker build --no-cache -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG -f "Develop & Deploy a REST API/weatherAPI/Dockerfile" .
        echo "Pushing image to Docker Hub..."
        docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG"
