name: Build & Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        id: login-docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, tag, and push the image to Docker Hub
        id: build-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPOSITORY: weatherapi
          IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit_hash }}
        run: |
          # Build a docker container and push it to Docker Hub
          docker build --no-cache -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest -f "Develop & Deploy a REST API/weatherAPI/Dockerfile" .
          echo "Pushing image to Docker Hub..."
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_TAG"
